name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
# projects: ["octo-org/1", "octo-org/44"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: macOS 15.6
          - **APP version**: v.1.0.0
      value: |
          - OS:
          - APP version:
      render: markdown
    validations:
      required: true