use crate::hosts_parser;
use std::process::Command;
use tauri::{command, Manager};
use tokio::fs;

use tauri::AppHandle;

#[command]
pub async fn write_file(
    app_handle: tauri::AppHandle,
    file_name: String,
    content: String,
    is_active: bool,
) -> Result<(), String> {
    hosts_parser::validate_hosts_file(&app_handle, &content).await?;

    let dir = app_handle.path().app_data_dir().unwrap();
    let file_path = dir.join("files").join(file_name);

    fs::write(file_path, &content)
        .await
        .map_err(|e| e.to_string())?;

    if is_active {
        write_system_hosts(&app_handle, content).await?;
    }

    Ok(())
}

pub async fn write_system_hosts_from_file(
    app_handle: &AppHandle,
    file_name: &str,
) -> Result<(), String> {
    let dir = app_handle.path().app_data_dir().unwrap();
    let file_path = dir.join("files").join(file_name);

    let content = fs::read_to_string(file_path)
        .await
        .map_err(|e| e.to_string())?;

    hosts_parser::validate_hosts_file(&app_handle, &content).await?;

    write_system_hosts(&app_handle, content).await
}

// Should not be called directly from the frontend. Must call hosts_parser::validate_hosts_file before.
pub async fn write_system_hosts(app_handle: &AppHandle, content: String) -> Result<(), String> {
    let platform = tauri_plugin_os::platform();

    let final_content = format!(
        "# This file was generated by the Hedit app\n# Generated on: {}\n# --------------\n",
        chrono::Local::now()
    ) + &hosts_parser::parse_hosts_file(app_handle, &content).await?;

    if platform == "linux" {
        return update_hosts_file_sudo(final_content).await;
    } else if platform == "macos" {
        return update_hosts_file(final_content).await;
    } else {
        return Err(format!("Unsupported platform: {}", platform));
    }
}

pub async fn update_hosts_file(content: String) -> Result<(), String> {
    std::fs::write("/etc/hosts", &content).map_err(|e| e.to_string())?;
    Ok(())
}

pub async fn update_hosts_file_sudo(content: String) -> Result<(), String> {
    // Write content to temporary file first
    let temp_path = "/tmp/hedit_hosts_update";
    std::fs::write(temp_path, &content).map_err(|e| e.to_string())?;

    // Use pkexec with cp to copy temp file to /etc/hosts
    let output = Command::new("pkexec")
        .arg("cp")
        .arg(temp_path)
        .arg("/etc/hosts")
        .output()
        .map_err(|e| e.to_string())?;

    // Clean up temp file
    let _ = std::fs::remove_file(temp_path);

    if output.status.success() {
        Ok(())
    } else {
        Err(String::from_utf8_lossy(&output.stderr).to_string())
    }
}
