use crate::hosts_parser;
use std::process::Command;
use tauri::{command, Manager};
use tokio::fs;

use tauri::AppHandle;

const WINDOWS_HOSTS_PATH: &str = r"C:\Windows\System32\drivers\etc\hosts";
const LINUX_HOSTS_PATH: &str = "/etc/hosts";
const MACOS_HOSTS_PATH: &str = "/etc/hosts";

#[command]
pub fn get_hosts_path() -> String {
    let platform = tauri_plugin_os::platform();
    if platform == "windows" {
        WINDOWS_HOSTS_PATH.to_string()
    } else if platform == "linux" {
        LINUX_HOSTS_PATH.to_string()
    } else {
        MACOS_HOSTS_PATH.to_string()
    }
}

#[command]
pub async fn read_system_hosts() -> Result<String, String> {
    let platform = tauri_plugin_os::platform();
    let path = if platform == "windows" {
        WINDOWS_HOSTS_PATH
    } else if platform == "linux" {
        LINUX_HOSTS_PATH
    } else {
        MACOS_HOSTS_PATH
    };

    tokio::fs::read_to_string(path)
        .await
        .map_err(|e| e.to_string())
}

#[command]
pub async fn write_file(
    app_handle: tauri::AppHandle,
    file_name: String,
    content: String,
    is_active: bool,
) -> Result<(), String> {
    hosts_parser::validate_hosts_file(&app_handle, &content).await?;

    let dir = app_handle.path().app_data_dir().unwrap();
    let file_path = dir.join("files").join(file_name);

    fs::write(file_path, &content)
        .await
        .map_err(|e| e.to_string())?;

    if is_active {
        write_system_hosts(&app_handle, content).await?;
    }

    Ok(())
}

pub async fn write_system_hosts_from_file(
    app_handle: &AppHandle,
    file_name: &str,
) -> Result<(), String> {
    let dir = app_handle.path().app_data_dir().unwrap();
    let file_path = dir.join("files").join(file_name);

    let content = fs::read_to_string(file_path)
        .await
        .map_err(|e| e.to_string())?;

    hosts_parser::validate_hosts_file(&app_handle, &content).await?;

    write_system_hosts(&app_handle, content).await
}

// Should not be called directly from the frontend. Must call hosts_parser::validate_hosts_file before.
pub async fn write_system_hosts(app_handle: &AppHandle, content: String) -> Result<(), String> {
    let platform = tauri_plugin_os::platform();

    let final_content = format!(
        "# This file was generated by the Hedit app\n# Generated on: {}\n# --------------\n",
        chrono::Local::now()
    ) + &hosts_parser::parse_hosts_file(app_handle, &content).await?;

    if platform == "linux" {
        return update_hosts_file_sudo(final_content).await;
    } else if platform == "macos" {
        return update_hosts_file_macos(final_content).await;
    } else if platform == "windows" {
        return update_hosts_file_windows(final_content).await;
    } else {
        return Err(format!("Unsupported platform: {}", platform));
    }
}

pub async fn update_hosts_file_macos(content: String) -> Result<(), String> {
    std::fs::write(MACOS_HOSTS_PATH, &content).map_err(|e| e.to_string())?;
    Ok(())
}

pub async fn update_hosts_file_windows(content: String) -> Result<(), String> {
    std::fs::write(WINDOWS_HOSTS_PATH, &content).map_err(|e| {
        if e.kind() == std::io::ErrorKind::PermissionDenied {
            return runas_elevation_windows(content);
        }
        e.to_string()
    })?;

    Ok(())
}

fn runas_elevation_windows(content: String) -> String {
    let temp_path = std::env::temp_dir().join("hedit_hosts_update");
    if let Err(e) = std::fs::write(&temp_path, &content) {
        return format!("Failed to write temp file: {}", e);
    }

    let temp_path_str = temp_path.to_string_lossy();
    let hosts_path = WINDOWS_HOSTS_PATH;

    let output = Command::new("powershell")
        .args([
            "-Command",
            &format!(
                "Start-Process -FilePath 'cmd' -ArgumentList '/c copy /Y \"{}\" \"{}\"' -Verb RunAs -Wait",
                temp_path_str, hosts_path
            ),
        ])
        .output();

    let _ = std::fs::remove_file(&temp_path);

    match output {
        Ok(output) => {
            if output.status.success() {
                String::new()
            } else {
                let stderr = String::from_utf8_lossy(&output.stderr);
                let stdout = String::from_utf8_lossy(&output.stdout);
                format!("Elevation failed: {} {}", stderr, stdout)
            }
        }
        Err(e) => format!("Failed to run elevation: {}", e),
    }
}

pub async fn update_hosts_file_sudo(content: String) -> Result<(), String> {
    let temp_path = "/tmp/hedit_hosts_update";
    std::fs::write(temp_path, &content).map_err(|e| e.to_string())?;

    let output = Command::new("pkexec")
        .arg("cp")
        .arg(temp_path)
        .arg(LINUX_HOSTS_PATH)
        .output()
        .map_err(|e| e.to_string())?;

    // Clean up temp file
    let _ = std::fs::remove_file(temp_path);

    if output.status.success() {
        Ok(())
    } else {
        Err(String::from_utf8_lossy(&output.stderr).to_string())
    }
}
